### ISSUE TITLE
Possible Volume Label Syntax Error

### ISSUE THREAD

**Issue by dtjunkie** [ianalis/scraper2022#2]
The program returned an error while attempting to retrieve data of election result from Brgy. Fuentes in Banate,Iloilo.

Error Description:
OS Error: [WinError 123]: The filename, directory name, or volume label syntax is incorrect:  'data\\results\\REGION VI\\ILOILO\\BANATE\\FUENTES*'

I think it has to do with the syntax of the name of the barangay.

![Screenshot 2022-08-10 005956](https://user-images.githubusercontent.com/90781857/183854650-929af39e-cc1f-4b7c-b1c3-d80675794d19.png)

**Comment by dtjunkie** [comment]
I've added a line of code (highlighted) that will remove the asterisk mark from the file path name.  So far, the program is now working, but I'll continue to monitor as there might be other marks than the asterisk that might be included in the file path name.

![Screenshot 2022-08-11 011733](https://user-images.githubusercontent.com/90781857/183975810-100d2ac0-d4b5-43c6-8223-1a70a5fdf5a4.png)

**Comment by ianalis** [comment]
This is not an issue on *nix systems. I suggest that instead of removing the asterisk, replace it with something else instead (for example, the plus sign). I think the names are from the PSGC so it's better to make the transformation reversible to keep compatibility with it. 

You may submit a PR after revising the code. Thanks!

**Comment by dtjunkie** [comment]
Hi Ian!

I've already submitted a PR for the revision. You can check it out for your approval. Thanks!
